// <auto-generated />
using FamousPortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FamousPortal.Migrations
{
    [DbContext(typeof(MealContext))]
    [Migration("20200219141704_FamousPortal")]
    partial class FamousPortal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FamousPortal.Models.Meal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("available")
                        .HasColumnType("bit");

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<string>("mealDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("mealId")
                        .HasColumnType("int");

                    b.Property<string>("mealName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("mealPrice")
                        .HasColumnType("int");

                    b.Property<string>("nutritionValues")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Meal");
                });
#pragma warning restore 612, 618
        }
    }
}
