// <auto-generated />
using FamousPortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FamousPortal.Migrations
{
    [DbContext(typeof(MealContext))]
    [Migration("20200219161801_Sqlite")]
    partial class Sqlite
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("FamousPortal.Models.Meal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("available")
                        .HasColumnType("INTEGER");

                    b.Property<int>("categoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("mealDescription")
                        .HasColumnType("TEXT");

                    b.Property<int>("mealId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("mealName")
                        .HasColumnType("TEXT");

                    b.Property<int>("mealPrice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nutritionValues")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Meal");
                });
#pragma warning restore 612, 618
        }
    }
}
